name: Cross-platform Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
      fail-fast: false  # Continue testing other targets if one fails
    
    steps:
    - uses: actions/checkout@v4
    
    # Install Rust (hopefully) #
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    # Install specific cross-compilation tools #
    - name: Install ARM toolchain
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          libc6-dev-arm64-cross
    
    - name: Install x86 toolchain
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-x86-64-linux-gnu \
          g++-x86-64-linux-gnu
    
    # environment variable specifically for ARM #
    - name: Build
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      run: cargo build --target ${{ matrix.target }} --release
