---
name: Cross-platform Shell Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shell-tests:
    strategy:
      matrix:
        include:
          - platform: linux-x64
            os: ubuntu-latest
            shell: bash
          - platform: linux-x64
            os: ubuntu-latest
            shell: zsh
          - platform: linux-x64
            os: ubuntu-latest
            shell: fish
          - platform: linux-x64
            os: ubuntu-latest
            shell: ksh
          - platform: linux-arm64
            os: ubuntu-latest
            shell: bash
          - platform: macos-x64
            os: macos-latest
            shell: bash
          - platform: macos-x64
            os: macos-latest
            shell: zsh
          - platform: macos-x64
            os: macos-latest
            shell: fish
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          install_linux() {
            sudo apt-get update
            sudo apt-get install -y $1 jq
          }
          install_macos() {
            brew install jq
            if [[ "$1" == "fish" ]]; then
              brew install fish
            fi
          }
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            install_linux "${{ matrix.shell }}"
          else
            install_macos "${{ matrix.shell }}"
          fi

      - name: Build release binary
        run: cargo build --release

      - name: Setup shell history
        run: |
          setup_history() {
            echo "[shell]" > ~/.pastrc
            echo "shell_type = \"$1\"" >> ~/.pastrc
            if [[ "$1" == "fish" ]]; then
              echo "config_file = \".config/fish/config.fish\"" >> ~/.pastrc
              mkdir -p ~/.local/share/fish
              echo "- cmd: ls" > ~/.local/share/fish/fish_history
              echo "  when: $(date +%s)" >> ~/.local/share/fish/fish_history
            else
              echo "config_file = \".${1}rc\"" >> ~/.pastrc
              echo "ls" > ~/.${1}_history
            fi
          }
          setup_history "${{ matrix.shell }}"

      - name: Run basic commands
        run: |
          ls > /dev/null
          pwd > /dev/null

      - name: Run tests
        run: |
          test_shell() {
            echo "Testing $1 shell"
            ./target/release/past --brief || exit 1
            ./target/release/past -s "ls" | grep -q "ls" || exit 1
          }
          test_shell "${{ matrix.shell }}"
